[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = [
    { name = "Ashok B", email = "author@example.com" }
]
requires-python = ">=3.11"
dependencies = [
    "cffi>=1.17.1",
]
